name: todo_app
description: "A simple todo application."
publish_to: 'none'

# 以下は、アプリケーションのバージョンおよびビルド番号を定義します。
# バージョン番号は、ドットで区切られた3つの数字（例: 1.2.43）で表され、
# その後にオプションのビルド番号（+で区切る）が続きます。
# Flutter のビルド時に `--build-name` および `--build-number` を指定することで、
# バージョン番号とビルド番号の両方を上書きすることができます。
# Android では、build-name は `versionName` として使用され、
# build-number は `versionCode` として使用されます。
# Android のバージョン管理についての詳細は、以下を参照してください:
# https://developer.android.com/studio/publish/versioning
# iOS では、build-name は `CFBundleShortVersionString` として使用され、
# build-number は `CFBundleVersion` として使用されます。
# iOS のバージョン管理についての詳細は、以下を参照してください:
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windows では、build-name は製品およびファイルバージョンの
# メジャー、マイナー、パッチ部分として使用され、
# build-number はビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# `dependencies` は、パッケージが動作するために必要な
# 他のパッケージを指定します。
# 依存関係を最新バージョンに自動更新するには、
# `flutter pub upgrade --major-versions` を実行してください。
# あるいは、以下のバージョン番号を手動で更新し、
# `pub.dev` で最新バージョンを確認することもできます。
# 更新可能な依存関係を確認するには、`flutter pub outdated` を実行してください。
dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

# 以下のセクションは、Flutter パッケージに特化した内容です。
flutter:

  # 以下の行により、Material Icons フォントがアプリケーションに
  # 含まれ、`MaterialIcons` クラスのアイコンを使用できるようになります
  uses-material-design: true

  # アセットをアプリケーションに追加するには、
  # 以下のように `assets` セクションを追加してください:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 画像アセットは、解像度ごとのバリエーションを指定することもできます。
  # 詳細は以下を参照してください:
  # https://flutter.dev/to/resolution-aware-images

  # パッケージ依存関係からアセットを追加する方法については、
  # 以下を参照してください:
  # https://flutter.dev/to/asset-from-package

  # カスタムフォントをアプリケーションに追加するには、
  # `flutter` セクション内に `fonts` セクションを追加してください。
  # 各フォント設定には、`family` キーでフォントファミリー名を指定し、
  # `fonts` キーでフォントのアセットパスとその他の属性を設定します。
  # 例:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存関係からフォントを追加する方法については、
  # 以下を参照してください:
  # https://flutter.dev/to/font-from-package